<?php

/*
	Extra Posting
	https://github.com/JacksiroKe
	Add extra postingfield(s) on the question form
	
*/

return array(
	'extra_posting_count_label' => 'Extra field count',
	'extra_posting_count_note' => '',
	'extra_posting_maxfile_size_label' => 'Max file size',
	'extra_posting_maxfile_size_note' => '',
	'extra_posting_only_image_label' => 'Permit only images (jpeg,png,gif)',
	'extra_posting_only_image_note' => '',
	'extra_posting_image_maxwidth_label' => 'Max image width',
	'extra_posting_image_maxwidth_note' => '',
	'extra_posting_image_maxheight_label' => 'Max image height',
	'extra_posting_image_maxheight_note' => '',
	'extra_posting_thumb_size_label' => 'Thumbnail width of attached image',
	'extra_posting_thumb_size_note' => '',
	'extra_posting_lightbox_effect_label' => 'Enable lightbox effect',
	'extra_posting_lightbox_effect_note' => '',
	'extra_posting_active_label' => 'Enable field^',
	'extra_posting_prompt_label' => 'Label on question form:',
	'extra_posting_prompt_default' => 'field^',
	'extra_posting_prompt_note' => '',
	'extra_posting_prompt_error' => 'Input label on question form.',
	'extra_posting_note_label' => 'Explanation on question form - HTML allowed:',
	'extra_posting_note_note' => '',
	'extra_posting_type_label' => 'Type:',
	'extra_posting_type_text' => 'textbox',
	'extra_posting_type_textarea' => 'textarea',
	'extra_posting_type_checkbox' => 'checkbox',
	'extra_posting_type_select' => 'selectbox',
	'extra_posting_type_radio' => 'radiobutton',
	'extra_posting_type_file' => 'file',
	'extra_posting_type_files' => 'files',
	'extra_posting_type_record' => 'record',
	'extra_posting_type_note' => '',
	'extra_posting_option_label' => 'Options:',
	'extra_posting_option_default' => '',
	'extra_posting_option_note' => 'Textarea ex: 5 (this is rows)<BR/>Checkbox ex: OFF==0||ON==1 / NO==0||YES==1<BR/>Select/Radio ex: ||label1==value1||label2==value2||label3==value3<BR/>File ex:Combine allowed file extensions by comma(,)<BR/>Program ex: @EVAL return \'||label1==value1||label2==value2\';',
	'extra_posting_option_error' => 'Textarea ex: 5 (this is rows)<BR/>Checkbox ex: OFF==0||ON==1 / NO==0||YES==1<BR/>Select/Radio ex: ||label1==value1||label2==value2||label3==value3<BR/>File ex:Combine allowed file extensions by comma(,)<BR/>Program ex: @EVAL return \'||label1==value1||label2==value2\';',
	'extra_posting_option_ext_error' => 'Only ^ file types are allowed.',
	'extra_posting_attr_label' => 'Attributes:',
	'extra_posting_attr_note' => 'Note: Other attributes of input tag in accordance with rule of HTML.<BR/>Textbox ex: maxlength="20"<BR/>Select ex: size="3"',
	'extra_posting_default_label' => 'Default value:',
	'extra_posting_default_default' => '',
	'extra_posting_default_note' => '',
	'extra_posting_form_pos_label' => 'Position on question form:',
	'extra_posting_form_pos_top' => 'Top',
	'extra_posting_form_pos_custom' => 'Below custom text',
	'extra_posting_form_pos_title' => 'Below title',
	'extra_posting_form_pos_category' => 'Below category',
	'extra_posting_form_pos_content' => 'Below content',
	'extra_posting_form_pos_extra' => 'Below extra field of Q2A',
	'extra_posting_form_pos_tags' => 'Below tags',
	'extra_posting_form_pos_notify' => 'Below notify',
	'extra_posting_form_pos_bottom' => 'Bottom',
	'extra_posting_form_pos_note' => '',
	'extra_posting_display_label' => 'Show on question page',
	'extra_posting_display_note' => '',
	'extra_posting_label_label' => 'Label on question page:',
	'extra_posting_label_default' => 'field^',
	'extra_posting_label_note' => '',
	'extra_posting_label_error' => 'Input label on question page.',
	'extra_posting_page_pos_label' => 'Position on question page:',
	'extra_posting_page_pos_upper' => 'Upper content',
	'extra_posting_page_pos_inside' => 'Inside content',
	'extra_posting_page_pos_below' => 'Below content',
	'extra_posting_page_pos_note' => 'When you chose "Inside content", explain on "Explanation on question form" that Asker has to include tag( ^ ) in contents.',
	'extra_posting_hide_blank_label' => 'Hide on question page if blank',
	'extra_posting_hide_blank_note' => '',
	'extra_posting_required_label' => 'Input is required',
	'extra_posting_required_note' => '',
	'extra_posting_required_message' => 'Please enter something in "^".<BR/>',
	'extra_posting_save_button' => 'Save Changes',
	'extra_posting_dfl_button' => 'Reset Defaults (Discard Settings)',
	'extra_posting_saved_message' => 'Plugin settings saved',
	'extra_posting_reset_message' => 'Plugin settings reset',
	'extra_posting_remove' => 'remove',
	'extra_posting_nav' => 'Extra Posting',
);

/*
	Omit PHP closing tag to help avoid accidental output
*/